# Generated by Django 2.1.7 on 2019-02-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('created_date', models.DateTimeField()),
                ('private', models.CharField(choices=[('0', 'Private'), ('1', 'Public')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('edits', models.ManyToManyField(related_name='editor_of', to='lists.List')),
                ('owns', models.ManyToManyField(related_name='owner_of', to='lists.List')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='editors',
            field=models.ManyToManyField(related_name='owner', to='lists.User'),
        ),
        migrations.AddField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editors', to='lists.User'),
        ),
    ]
