# Generated by Django 2.1.7 on 2019-02-27 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0003_auto_20190227_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='edits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='owns',
        ),
        migrations.AlterField(
            model_name='list',
            name='editors',
            field=models.ManyToManyField(blank='True', related_name='editors', to='lists.Profile'),
        ),
        migrations.AlterField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='lists.Profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='edits',
            field=models.ManyToManyField(related_name='editor_of', to='lists.List'),
        ),
        migrations.AddField(
            model_name='profile',
            name='owns',
            field=models.ManyToManyField(related_name='owner_of', to='lists.List'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
