# Generated by Django 2.1.7 on 2019-02-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20190228_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='list',
            name='owner',
        ),
        migrations.AlterField(
            model_name='profile',
            name='edits',
            field=models.ManyToManyField(related_name='editors', to='lists.List'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='owns',
            field=models.ManyToManyField(related_name='owner', to='lists.List'),
        ),
    ]
