# Generated by Django 2.1.7 on 2019-02-28 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20190228_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='owns',
        ),
        migrations.AddField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='lists.Profile'),
        ),
    ]
