# Generated by Django 2.1.7 on 2019-02-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20190228_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='owner',
            field=models.OneToOneField(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.Profile'),
        ),
    ]
