# Generated by Django 2.1.7 on 2019-02-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_auto_20190228_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='edits',
            field=models.ManyToManyField(related_name='editors', to='lists.List'),
        ),
    ]
