# Generated by Django 2.1.7 on 2019-02-28 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0014_auto_20190228_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='editors',
            field=models.ManyToManyField(blank='True', related_name='editors', to='lists.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='owns',
            field=models.ManyToManyField(related_name='owner_of', to='lists.List'),
        ),
        migrations.AlterField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='lists.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='edits',
            field=models.ManyToManyField(related_name='editor_of', to='lists.List'),
        ),
    ]
