# Generated by Django 2.1.7 on 2019-02-28 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0015_auto_20190228_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='edits',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='owns',
        ),
        migrations.AddField(
            model_name='list',
            name='viewers',
            field=models.ManyToManyField(null=True, related_name='viewer_of', to='lists.Profile'),
        ),
        migrations.AlterField(
            model_name='list',
            name='editors',
            field=models.ManyToManyField(null=True, related_name='editor_of', to='lists.Profile'),
        ),
        migrations.AlterField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_of', to='lists.Profile'),
        ),
    ]
