# Generated by Django 2.1.7 on 2019-02-28 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0017_auto_20190228_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_of', to='lists.Profile'),
        ),
        migrations.AlterField(
            model_name='list',
            name='private',
            field=models.CharField(choices=[('0', 'Private'), ('1', 'Public')], max_length=1, null=True),
        ),
    ]
