# Generated by Django 2.1.7 on 2019-02-28 23:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0019_auto_20190228_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='editors',
            field=models.ManyToManyField(blank=True, null=True, related_name='editor_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='private',
            field=models.CharField(blank=True, choices=[('0', 'Private'), ('1', 'Public')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='viewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='viewer_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
