# Generated by Django 2.1.7 on 2019-03-07 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lists.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0020_auto_20190228_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=models.SET(lists.models.get_user_deleted), related_name='creator_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Text'), ('1', 'Itemized')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.List'),
        ),
    ]
