# Generated by Django 2.1.7 on 2019-03-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0021_auto_20190307_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='private',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
