# Generated by Django 2.1.7 on 2019-03-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0022_auto_20190307_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='private',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.BooleanField(blank=True, choices=[('0', 'Text'), ('1', 'Itemized')], max_length=1, null=True),
        ),
    ]
